package com.example.service

import android.app.Notification
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import com.example.data.AppDatabase
import com.example.data.PreferencesManager
import com.example.parser.MobileMoneyParser
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class TransactionNotificationListener : NotificationListenerService() {

  override fun onNotificationPosted(sbn: StatusBarNotification?) {
    super.onNotificationPosted(sbn)
    if (sbn == null) return

    val prefs = PreferencesManager(applicationContext)
    if (!prefs.isAutoLogNotificationEnabled) return

    val pkg = sbn.packageName.orEmpty().lowercase()
    // Ignore notifications generated by MaliTrack itself to prevent feedback loop
    if (pkg == packageName.lowercase()) return

    val extras = sbn.notification.extras ?: return
    val title = extras.getString(Notification.EXTRA_TITLE).orEmpty()
    val text = extras.getCharSequence(Notification.EXTRA_TEXT)?.toString().orEmpty()
    val bigText = extras.getCharSequence(Notification.EXTRA_BIG_TEXT)?.toString().orEmpty()

    val combinedContent = when {
      bigText.isNotBlank() -> "$title $bigText"
      text.isNotBlank() -> "$title $text"
      else -> title
    }

    if (combinedContent.isBlank()) return

    // Parse transaction using parser
    val parsed = MobileMoneyParser.parseSingleMessage(combinedContent) ?: return
    if (parsed.amount <= 0.0) return

    CoroutineScope(Dispatchers.IO).launch {
      try {
        val db = AppDatabase.getDatabase(applicationContext)
        val dao = db.financeDao()

        // Deduplicate reference code if available
        if (parsed.referenceCode.isNotBlank()) {
          val existing = dao.getTransactionByReference(parsed.referenceCode)
          if (existing != null) return@launch
        }

        val entity = parsed.toEntity().copy(
          date = sbn.postTime,
          notes = "Auto-captured from notification ($pkg)"
        )
        dao.insertTransaction(entity)
      } catch (e: Exception) {
        e.printStackTrace()
      }
    }
  }
}
